### ISSUE TITLE
Ctrl+Shift+click replaces split tab instead of opening another one

### ISSUE THREAD

**Issue by nazar-pc** [parallaxe/OpenInSplittedTab#10]
When I do Ctrl+Shift+click and there is a file opened in split panel it is replaced with new file instead of opening new tab. I think it is related to recent changes in PhpStorm.

Demo: https://www.youtube.com/watch?v=wpSRUXCiPZY

I'm using latest EAP build PS-171.4424.11.

**Comment by parallaxe** [comment]
You refer to the action "Open in splitted (new) tab" which you assigned the shortcut Ctrl+Shift+click, right? Because replacing the existing tab is the default-behaviour for the "Open in splitted tab"-action. 
I can't reproduce the behaviour shown in the video. I downloaded PhpStorm 2017.1.3, Build #PS-171.4424.11, built on April 26, 2017 for Mac and Linux. Performing the action either by right-click
 -> Go To -> Open in splitted (new) tab or by assigning the Ctrl+Shift+click-shortcut to the action, it always opens a new tab as expected.
Are the shown files .php- or .html-files? Is the problem related to a specific project or true for all projects? May you guide me to a project + filenames where the problem happens

**Comment by nazar-pc** [comment]
I've assigned a shortcut for `Open in splitted tab` action, not `Open in splitted (new) tab`. After re-assigning shortcut to the latter, everything works as expected, thanks!

**Comment by parallaxe** [comment]
Glad to hear that, thanks for the update.
